"""Stage a synthetic inbound email carrying one oversized, sideways
photo. Used by scripts/agent-sideways-picture-roundtrip to exercise
the image-editing subagent end-to-end: parent should triage with
view_site_image, delegate rotate+resize to edit_images, then embed in
gallery.html.

The image is a 4000x3000 JPEG with EXIF orientation 1 (no EXIF
rotation), generated by drawing a portrait scene (sky on top, grass
on bottom, red bar at the top edge) and rotating the pixel data 90
CW. So the file LOOKS sideways: sky on the right, grass on the left.
The email body explicitly tells Cyndibot it's sideways and too big.

Sender prefix is `smoketest-` so the changelog entry will be tagged
[TEST] per the system prompt's convention.
"""

import secrets
from datetime import datetime, timezone
from email.message import EmailMessage
from email.utils import format_datetime, make_msgid
from io import BytesIO

import boto3
from PIL import Image, ImageDraw

BUCKET = "cyndibot-incoming-emails"
PREFIX = "emails/"
SENDER = "smoketest-sideways@cyndibot.jessitron.honeydemo.io"
RECIPIENT = "cyndi@cyndibot.jessitron.honeydemo.io"


def make_sideways_jpeg() -> bytes:
    upright = Image.new("RGB", (3000, 4000), color=(135, 206, 235))
    draw = ImageDraw.Draw(upright)
    draw.rectangle([0, 2000, 3000, 4000], fill=(80, 160, 80))
    draw.rectangle([0, 0, 3000, 200], fill=(220, 50, 50))

    sideways = upright.rotate(-90, expand=True)
    buf = BytesIO()
    sideways.save(buf, format="JPEG", quality=85)
    return buf.getvalue()


def build_message() -> bytes:
    msg = EmailMessage()
    msg["From"] = SENDER
    msg["To"] = RECIPIENT
    msg["Subject"] = "garden picture for the site"
    msg["Date"] = format_datetime(datetime.now(timezone.utc))
    msg["Message-ID"] = make_msgid(domain="cyndibot.jessitron.honeydemo.io")
    msg.set_content(
        "Hi Cyndibot,\n"
        "\n"
        "Here's a picture of my garden -- please add it to gallery.html.\n"
        "It's sideways and probably too big -- can you fix it so it\n"
        "looks right on the page?\n"
        "\n"
        "Thanks!\n"
        "-- smoketest-sideways\n"
    )

    msg.add_attachment(
        make_sideways_jpeg(),
        maintype="image",
        subtype="jpeg",
        filename="garden.jpg",
    )

    return msg.as_bytes()


def main() -> None:
    key = f"{PREFIX}smoke-sideways-{secrets.token_urlsafe(12)}"
    boto3.client("s3").put_object(Bucket=BUCKET, Key=key, Body=build_message())
    print(key)


if __name__ == "__main__":
    main()
